In [2]:
from jupyter_innotater import *
import numpy as np, os

objs = sorted(os.listdir('./frame_images/'))

repeats = 8

# Per-photo data
classes1 = ['Main','people', 'vehicle']
targets_type = np.zeros((len(objs), 4), dtype='int') # Column vector containing class index

# Repeats within each photo
targets_bboxes = np.zeros((len(objs), repeats, 4), dtype='int') # (x,y,w,h) for each animal


Innotater( 
    ImageInnotation(objs, path='./frame_images/', width=400, height=300), 
    [
        MultiClassInnotation(targets_type, name='objs', classes=classes1, dropdown=False),
        RepeatInnotation(
            (BoundingBoxInnotation, targets_bboxes),
             max_repeats=repeats, min_repeats=1
        )
    ]
)

Innotater(children=(HBox(children=(VBox(children=(ImagePad(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x0…

In [12]:
import pandas as pd
#df = pd.DataFrame(targets_type,targets_bboxes,columns=['x','y','w','h'])
df = pd.DataFrame(targets_type,targets_bboxes)
#df.insert(0,'bounding_boxes2.csv',targets_bboxes)
df.to_csv('./bounding_boxes5.csv',index=True)

In [10]:
print('Class Indices', targets_type[:2]) # Just display the first 2 to save space
print('Bounding Boxes', targets_bboxes[:30])

Class Indices [[0 1 0 0]
 [0 1 0 0]]
Bounding Boxes [[[  14   20 1896 1027]
  [  47  635  547  384]
  [ 993  572  326  134]
  [1363  539  326  115]
  [1732  534  110  230]
  [ 705  529  110  144]
  [   0    0    0    0]
  [   0    0    0    0]]

 [[  14   20 1896 1027]
  [1003  572  307  154]
  [1281  553  312  115]
  [1727  543  120  240]
  [   0    0    0    0]
  [   0    0    0    0]
  [   0    0    0    0]
  [   0    0    0    0]]

 [[  14   20 1896 1027]
  [1761  596   72   91]
  [1823  596   48   82]
  [1151  630  283  106]
  [1228  668   72  221]
  [   0    0    0    0]
  [   0    0    0    0]
  [   0    0    0    0]]

 [[  14   20 1896 1027]
  [ 460  555  710  403]
  [1627  670  115  182]
  [1243  704  115  312]
  [   0    0    0    0]
  [   0    0    0    0]
  [   0    0    0    0]
  [   0    0    0    0]]

 [[  14   20 1896 1027]
  [ 998  593  379  187]
  [1651  665   82  163]
  [1262  718   86  283]
  [   0    0    0    0]
  [   0    0    0    0]
  [   0    0    0    0]
  [ 